//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class usalechildren
    {
        public int UserId { get; set; }
        public int ChildId { get; set; }
        public int Reviewer { get; set; }
        public System.DateTime AffectTime { get; set; }
        public string Comment { get; set; }
    }
}
