//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int UserId { get; set; }
        public int PhoneNum { get; set; }
        public string Name { get; set; }
        public string FedId { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> FirstAccessTime { get; set; }
        public Nullable<System.DateTime> LastAccessTime { get; set; }
        public string Pwd { get; set; }
    }
}
