//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class userjobinfo
    {
        public int UserId { get; set; }
        public string Job { get; set; }
        public string Place { get; set; }
        public Nullable<int> JobOrder { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> LeaveTime { get; set; }
    }
}
